include: package:lint/analysis_options.yaml

analyzer:
  exclude:
    - build/**
    - lib/generated_plugin_registrant.dart
    - lib/**/*.g.dart
    - lib/**/*.gr.dart
    - lib/**/*.freezed.dart
    - lib/*.config.dart
  strong-mode:
    implicit-casts: false

linter:
  rules:
    sort_pub_dependencies: false
    avoid_classes_with_only_static_members: false
    avoid_positional_boolean_parameters: false
    constant_identifier_names: false
    prefer_single_quotes: true
