targets:
  $default:
    builders:
      reflectable:
        generate_for:
          - lib/main.dart
          # - lib/src/presentation/core/widgets/render_clases/*.dart
          - lib/src/presentation/core/widgets/render_clases/**.dart
