targets:
  $default:
    builders:
      reflectable:
        generate_for:
          ## Presentation
          # Fields Widgets to Show and input Data
          - lib/src/presentation/core/widgets/render_clases/

          ## Infraestructure
          # FieldValue Models
          # - lib/src/presentation/core/instanciate/
