name: geobase
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  dartz: ^0.10.0
  flash: ^1.5.1
  flutter_bloc: ^7.3.0
  flutter_image: ^4.0.1
  flutter_map: ^0.13.1
  flutter_lyform: ^0.5.0
  freezed_annotation: ^0.14.1
  get_it: ^7.2.0
  injectable: ^1.3.0
  json_annotation: ^4.0.1
  latlong2: ^0.8.0
  location: ^4.3.0
  shared_preferences: ^2.0.5
  sliding_up_panel: ^2.0.0+1
  rxdart: ^0.27.2
  beamer:
    git:
      url: https://github.com/slovnicki/beamer.git
      path: package
      ref: 2015b04c79bf139d2df32ea62cba9f5d489433b2
  flutter_colorpicker: ^0.6.0
  path_provider: ^2.0.7
  sqfentity: ^2.0.0
  sqfentity_gen: ^2.0.0
  reflectable: ^3.0.1
  flutter_form_bloc: ^0.20.6
  image_picker: ^0.8.4+4
  file_picker: ^4.2.4
  open_file: ^3.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.11.5
  build_verify: ^2.0.0
  lint: ^1.6.0
  freezed: ^0.14.1
  injectable_generator: ^1.2.0
  json_serializable: ^4.0.2
  # customization
  # flutter_native_splash
  # flutter_launcher_icons
  # code checks

flutter:
  uses-material-design: true

  # assets:
  #   - assets/images/

  fonts:
    - family: Aller
      fonts:
        - asset: assets/fonts/Aller_Std_Rg.ttf
        - asset: assets/fonts/Aller_Std_It.ttf
          style: italic
        - asset: assets/fonts/Aller_Std_Bd.ttf
          weight: 700
