name: geobase
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.1+1

environment:
  sdk: '^3.0.3'
  flutter: '3.10.3'

dependencies:
  flutter:
    sdk: flutter
  dartz: ^0.10.1
  record: ^4.0.0             # Para grabar audio
  permission_handler: ^10.4.0
  excel: ^2.0.0  # Para generar archivos Excel
  video_player: ^2.7.0
  file_picker: ^7.0.2
  flash: ^3.0.5+2
  flutter_bloc: ^8.1.1
  flutter_image: ^4.1.4
  flutter_map: ^6.1.0
  flutter_lyform: ^0.13.0+1
  flutter_riverpod: ^2.0.2
  flutter_form_bloc: ^0.30.1
  flutter_iconpicker: 3.2.4
  freezed_annotation: ^2.2.0
  get_it: ^7.2.0
  injectable: ^2.3.5
  json_annotation: ^4.7.0
  latlong2: ^0.9.1
  location: ^5.0.3
  shared_preferences: ^2.0.15
  sliding_up_panel: ^2.0.0+1
  rxdart: ^0.27.5
  beamer: 1.5.3
  flutter_colorpicker: ^1.0.3
  path_provider: ^2.0.11
  sqfentity: ^2.3.0+5
  sqfentity_gen: ^2.3.0+4
  reflectable: ^3.0.10
  image_picker: ^1.0.7
  open_file: ^3.2.1
  video_thumbnail: ^0.5.3
  path: ^1.8.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.9
  # build_verify: ^3.0.0
  flutter_lints: ^3.0.1
  freezed: ^2.2.0
  injectable_generator: ^2.1.4
  json_serializable: ^6.5.3
  # customization
  flutter_native_splash:
  flutter_launcher_icons:
  # code checks

flutter:
  uses-material-design: true

  assets:
    - assets/icons/

  fonts:
    - family: Aller
      fonts:
        - asset: assets/fonts/Aller_Std_Rg.ttf
        - asset: assets/fonts/Aller_Std_It.ttf
          style: italic
        - asset: assets/fonts/Aller_Std_Bd.ttf
          weight: 700

flutter_icons:
  android: 'launcher_icon'
  ios: true
  adaptive_icon_background: '#ffffff'
  image_path: 'assets/icons/icon_v2.png'
  # adaptive_icon_foreground: 'assets/icons/icon_v1.png'
  # remove_alpha_ios: true

flutter_native_splash:
  # image: assets/splash.png
  color: 'ffffff'
  color_dark: '1b1b1f'
